name: Tests

on:
    push:
        branches:
            - "main"
    pull_request:

jobs:
    tests:
        strategy:
            fail-fast: false
            matrix:
                nvim_version:
                    - v0.9.0
                    - v0.9.1
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: rhysd/action-setup-vim@v1
              with:
                  neovim: true
                  version: ${{ matrix.nvim_version }}
            - name: Run tests
              run: |
                set -e
                make test
                nvim -u NONE -E -R --headless +'helptags doc' +q
